import { z } from 'zod'
import { validCampaignId } from '@/lib/domain/ebay'

/** Server-side validation for every setting the admin console can edit
 * (each field in SETTING_GROUPS must have an entry; a unit test enforces it). */
export const SETTING_VALIDATORS: Record<string, z.ZodType> = {
  'billing.premium_monthly_cents': z.number().int().min(100).max(100000),
  'billing.premium_annual_cents': z.number().int().min(100).max(1000000).nullable(),
  'billing.founder_monthly_cents': z.number().int().min(100).max(100000).nullable(),
  'billing.grace_period_days': z.number().int().min(0).max(30),
  'quota.free_per_period': z.number().int().min(0).max(1000),
  'quota.premium_per_period': z.number().int().min(0).max(10000),
  'quota.period': z.enum(['calendar_month', 'rolling_30_days']),
  'quota.count_rejected': z.boolean(),
  'listings.expiry_days': z.number().int().min(7).max(365),
  'listings.auto_approve_trusted': z.boolean(),
  'market.outlier_min_ratio': z.number().min(0).max(1),
  'market.floor_refresh_hours': z.number().min(1).max(48),
  'justtcg.raw_discover': z.boolean(),
  'market.snapshot_min_aud': z.number().min(0).max(100000),
  'justtcg.history_min_aud': z.number().min(0).max(100000),
  'drops.public_delay_minutes': z.number().int().min(0).max(10080),
  'drops.free_delay_minutes': z.number().int().min(0).max(10080),
  'drops.free_delayed_alerts': z.boolean(),
  'drops.price_drop_pct': z.number().int().min(1).max(90),
  'drops.suppress_above_rrp_pct': z.number().min(0).max(1000),
  'features.external_buy_fallback': z.boolean(),
  'images.tcgplayer_fallback': z.boolean(),
  'ebay.enabled': z.boolean(),
  'ebay.affiliate_enabled': z.boolean(),
  'ebay.campaign_id': z.string().refine(validCampaignId, 'An EPN campaign id is 10 digits').nullable(),
  'ebay.custom_id': z.string().regex(/^[A-Za-z0-9_-]{1,40}$/, 'Letters, numbers, - and _ only'),
  'site.announcement': z.string().max(200).nullable(),
  'stock.show_retailer_images': z.boolean(),
  'stock.default_interval_seconds': z.number().int().min(30).max(86400),
  'sightings.enabled': z.boolean(),
  'sightings.confirmations_needed': z.number().int().min(1).max(10),
  'sightings.confirmations_with_photo': z.number().int().min(0).max(10),
  'sightings.trusted_after': z.number().int().min(1).max(1000),
  'sightings.trusted_max_reject_pct': z.number().int().min(0).max(100),
  'sightings.daily_limit': z.number().int().min(1).max(100),
  'sightings.pending_expiry_minutes': z.number().int().min(30).max(2880),
  'sightings.gone_votes_to_close': z.number().int().min(1).max(10),
  'scouts.reward_every': z.number().int().min(0).max(1000),
  'scouts.reward_days': z.number().int().min(1).max(365),
  'deals.enabled': z.boolean(),
  'deals.min_discount_pct': z.number().int().min(5).max(90),
  'deals.auction_ending_minutes': z.number().int().min(15).max(1440),
  'deals.max_cards_per_run': z.number().int().min(10).max(1000),
  'deals.public_delay_minutes': z.number().int().min(0).max(10080),
}
