-- Store registry for the live stock monitor (docs/research/09-retailer-registry.json,
-- surveyed 2026-10-01 with our honest user agent from a non-AU cloud IP).
--
-- * Stores with an open, robots-allowed Shopify / WooCommerce catalogue feed are
--   monitored by the generic adapters (enabled; the first scan is a silent baseline).
-- * Stores that served a bot challenge / 403, or have no feed, are recorded with
--   blocked_reason and stay member-sightings-only (adapter 'none'). The workers
--   re-try nothing on their own; an admin can re-probe from the Sydney server.
-- * Existing custom adapters (JB Hi-Fi's Algolia monitor, Target's category
--   monitor, BIG W / Kmart blocked adapters) keep their adapter; only metadata
--   is refreshed for them.

insert into public.retailers (slug, name, base_url, adapter, enabled, platform, config, kind, state, blocked_reason, watch_interval_seconds, discovery_interval_seconds) values
  ('toysrus', 'Toys"R"Us Australia', 'https://www.toysrus.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-tcg"], "games": ["pokemon"]}'::jsonb, 'toy', null, null, 120, 300),
  ('light-of-cards', 'Light of Cards', 'https://lightofcards.com.au', 'shopify', true, 'shopify', '{"collections": ["ptcg-en", "one-piece-en"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'NSW'::public.au_state, null, 120, 300),
  ('pokebox', 'PokeBox Australia', 'https://www.pokebox.com.au', 'shopify', true, 'shopify', '{"collections": ["english-sealed-pokemon-trading-cards", "one-piece-card-game-english"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, null, 120, 300),
  ('trainer-town', 'Trainer Town', 'https://trainertown.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-cards", "one-piece-trading-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('good-games', 'Good Games', 'https://www.goodgames.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-tcg-scarlet-violet-sealed-product", "pokemon", "one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'NSW'::public.au_state, null, 120, 300),
  ('good-games-tcg', 'Good Games TCG (tcg subdomain)', 'https://tcg.goodgames.com.au', 'shopify', false, 'shopify', '{"collections": ["pokemon-sealed-products", "one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'NSW'::public.au_state, 'no-feed', 120, 300),
  ('gameology', 'Gameology', 'https://www.gameology.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-booster-boxes", "pokemon", "one-piece-booster-boxs", "one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('zing-pop-culture', 'ZiNG Pop Culture', 'https://www.zingpopculture.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'big-box', 'QLD'::public.au_state, 'challenge', 120, 300),
  ('eb-games', 'EB Games Australia', 'https://www.ebgames.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'big-box', 'QLD'::public.au_state, 'challenge', 120, 300),
  ('jb-hi-fi', 'JB Hi-Fi', 'https://www.jbhifi.com.au', 'shopify', false, 'shopify', '{"games": ["pokemon"]}'::jsonb, 'big-box', 'VIC'::public.au_state, 'no-feed', 120, 300),
  ('big-w', 'BIG W', 'https://www.bigw.com.au', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'big-box', 'NSW'::public.au_state, 'challenge', 120, 300),
  ('kmart', 'Kmart Australia', 'https://www.kmart.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'big-box', 'VIC'::public.au_state, 'challenge', 120, 300),
  ('target-au', 'Target Australia', 'https://www.target.com.au', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'big-box', 'VIC'::public.au_state, 'no-feed', 120, 300),
  ('myer', 'Myer', 'https://www.myer.com.au', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'department', 'VIC'::public.au_state, 'no-feed', 120, 300),
  ('david-jones', 'David Jones', 'https://www.davidjones.com', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'department', 'NSW'::public.au_state, 'no-feed', 120, 300),
  ('amazon-au', 'Amazon Australia', 'https://www.amazon.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'big-box', 'NSW'::public.au_state, 'challenge', 120, 300),
  ('kidstuff', 'Kidstuff', 'https://www.kidstuff.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon"], "games": ["pokemon"]}'::jsonb, 'toy', 'VIC'::public.au_state, null, 120, 300),
  ('mr-toys', 'Mr Toys Toyworld', 'https://www.mrtoys.com.au', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'toy', null, 'challenge', 120, 300),
  ('toyworld', 'Toyworld Australia', 'https://www.toyworld.com.au', 'shopify', true, 'shopify', '{"collections": ["trading-cards", "pokemon", "one-piece"], "games": ["pokemon"]}'::jsonb, 'toy', 'VIC'::public.au_state, null, 120, 300),
  ('ozzie-collectables', 'Ozzie Collectables', 'https://www.ozziecollectables.com', 'shopify', true, 'shopify', '{"collections": ["manufacturer-pokemon", "manufacturer-one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('cherry-collectables', 'Cherry Collectables', 'https://www.cherrycollectables.com.au', 'shopify', true, 'shopify', '{"collections": ["all-pokemon", "all-one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('gamerholic', 'Gamer Holic', 'https://gamerholic.com.au', 'shopify', true, 'shopify', '{"collections": ["english-pokemon-sets", "one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('tc-game', 'TC Game', 'https://tcgame.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-booster-boxes-and-packs", "one-piece-card-game-japanese-booster-boxes-packs"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('the-feisty-lizard', 'The Feisty Lizard', 'https://www.thefeistylizard.com.au', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'specialist', null, 'no-feed', 120, 300),
  ('pokemon-world-australia', 'Pokeworld Australia', 'https://www.pokemonworldaustralia.com', 'shopify', true, 'shopify', '{"collections": ["booster-boxes", "elite-trainer-boxes", "collection-tins-boxes", "booster-packs", "one-piece-booster-box"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('that-tcg-store', 'That TCG Store', 'https://thattcgstore.com', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, '403', 120, 300),
  ('mighty-collectibles', 'Mighty Collectibles', 'https://mightycollectibles.com.au', 'woocommerce', true, 'woocommerce', '{"categories": [{"id": 82, "slug": "pokemon"}, {"id": 116, "slug": "japanese-pokemon-cards"}, {"id": 237, "slug": "one-piece"}], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('cards-by-brammers', 'Cards by Brammers', 'https://www.cardsbybrammers.com.au', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'specialist', null, 'no-feed', 120, 300),
  ('cardbot', 'Cardbot', 'https://cardbot.com.au', 'shopify', true, 'shopify', '{"collections": ["english-pokemon-tcg", "one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('games-portal', 'Games Portal', 'https://gamesportal.com.au', 'shopify', true, 'shopify', '{"collections": ["one-piece-card-game"], "games": ["one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('good-deals-games', 'Good Deals Games (GD Games)', 'https://www.gdgames.com.au', 'shopify', true, 'shopify', '{"collections": ["english-pokemon-tcg", "one-piece-tcg"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'QLD'::public.au_state, null, 120, 300),
  ('jtoys', 'JToys', 'https://www.jtoys.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, 'challenge', 120, 300),
  ('mind-games', 'Mind Games', 'https://www.m-g.com.au', 'woocommerce', true, 'woocommerce', '{"categories": [{"id": 66, "slug": "pokemon"}, {"id": 603, "slug": "one-piece"}], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, null, 120, 300),
  ('kollecter', 'Kollecter', 'https://www.kollecter.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon", "english-one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'WA'::public.au_state, null, 120, 300),
  ('pocket-games', 'Pocket Games Australia', 'https://pocketgames.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-tcg-cards", "one-piece-tcg-cards"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'NSW'::public.au_state, null, 120, 300),
  ('pro-gamers', 'Pro Gamers Australia', 'https://progamers.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-sealed-booster-boxes", "one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('tcgroup-au', 'TCGroup AU', 'https://www.tcgroupau.com.au', 'shopify', true, 'shopify', '{"collections": ["english-pokemon", "english-one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, null, 120, 300),
  ('kawaii-collector', 'Kawaii Collector', 'https://kawaiicollector.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-sealed-products"], "games": ["pokemon"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('goldfields-games', 'Goldfields Toys & Games', 'https://goldfieldsgames.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-trading-card-game", "one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'toy', null, null, 120, 300),
  ('collectible-madness', 'Collectible Madness', 'https://collectiblemadness.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-trading-card-game", "one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('trainerhub', 'TrainerHub Australia', 'https://www.trainerhub.net.au', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'specialist', null, 'no-feed', 120, 300),
  ('hobby-collectors-australia', 'Hobby Collectors Australia', 'https://hobbycollectorsaustralia.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-sealed", "one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('drop-store', 'Drop Store Collectables', 'https://dropstore.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-tcg", "one-piece-tcg"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, null, 120, 300),
  ('pokesource', 'PokeSource Australia', 'https://pokesource.com.au', 'shopify', true, 'shopify', '{"collections": ["all", "one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, null, 120, 300),
  ('ace-collectibles', 'Ace Collectibles', 'https://www.acecollectibles.com.au', 'shopify', true, 'shopify', '{"collections": ["all-products-pokemon", "one-piece-1"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'SA'::public.au_state, null, 120, 300),
  ('leo-games', 'Leo Games', 'https://www.leogames.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon", "one-piece-card-game"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('trading-card-masters', 'Trading Card Masters', 'https://www.tradingcardmasters.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-english-tcg"], "games": ["pokemon"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('tcg-collectors', 'TCG Collectors', 'https://tcgcollectors.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, 'robots', 120, 300),
  ('loot-vault', 'Loot Vault', 'https://lootvault.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-tcg", "one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('vault-of-the-cards', 'Vault of the Cards', 'https://vaultofthecards.com.au', 'shopify', false, 'shopify', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, 'challenge', 120, 300),
  ('mint-collectables', 'Mint Collectables', 'https://mintcollectables.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon", "one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('grailborne', 'Grailborne', 'https://grailborne.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-tcg", "one-piece"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('gb-toys', 'GB Toys', 'https://gbtoys.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-tcg-english", "one-piece-english"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('eternal-magic', 'Eternal Magic', 'https://eternalmagic.cc', 'shopify', true, 'shopify', '{"collections": ["one-piece-sealed"], "games": ["one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('mochi-pals', 'Mochi Pals', 'https://www.mochipalaus.com', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'specialist', 'VIC'::public.au_state, 'no-feed', 120, 300),
  ('toyland-treasures', 'Toyland Treasures', 'https://www.toylandtreasures.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-cards-australia"], "games": ["pokemon"]}'::jsonb, 'specialist', 'VIC'::public.au_state, null, 120, 300),
  ('plenty-of-games', 'Plenty of Games', 'https://www.plentyofgames.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-sealed", "one-piece-sealed"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, null, 120, 300),
  ('good-games-adelaide', 'Good Games Adelaide', 'https://ggadelaide.com.au', 'shopify', false, 'shopify', '{"collections": ["pokemon"], "games": ["pokemon"]}'::jsonb, 'specialist', 'SA'::public.au_state, 'no-feed', 120, 300),
  ('mistys-collectables', 'Misty''s Collectables', 'https://mistyscollectables.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'QLD'::public.au_state, 'no-feed', 120, 300),
  ('card-traders-australia', 'Card Traders Australia', 'https://cardtradersaustralia.com.au', 'shopify', true, 'shopify', '{"collections": ["all"], "games": ["pokemon"]}'::jsonb, 'specialist', 'SA'::public.au_state, null, 120, 300),
  ('troll-australia', 'Troll Australia', 'https://www.trollaustralia.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon-sealed", "one-piece-sealed"], "games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('mystical-merchants', 'Mystical Merchants', 'https://mysticalmerchants.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', null, 'challenge', 120, 300),
  ('overhauled-games', 'Overhauled Games', 'https://overhauledgames.com.au', 'none', false, 'custom', '{"games": ["pokemon", "one-piece"]}'::jsonb, 'specialist', 'VIC'::public.au_state, 'challenge', 120, 300),
  ('chaotic-factory', 'Chaotic Factory', 'https://www.chaoticfactory.com.au', 'none', false, 'custom', '{"games": ["pokemon"]}'::jsonb, 'specialist', null, 'no-feed', 120, 300),
  ('mastercoins', 'Mastercoins', 'https://www.mastercoins.com.au', 'shopify', true, 'shopify', '{"collections": ["pokemon"], "games": ["pokemon"]}'::jsonb, 'specialist', null, null, 120, 300),
  ('curacards', 'CuraCards', 'https://curacards.com.au', 'shopify', false, 'shopify', '{"games": ["pokemon"]}'::jsonb, 'specialist', null, 'no-feed', 120, 300),
  ('monster-mart', 'Monster Mart', 'https://www.monstermart.com.au', 'shopify', false, 'shopify', '{"games": ["pokemon"]}'::jsonb, 'specialist', 'QLD'::public.au_state, 'no-feed', 120, 300)
on conflict (slug) do update set
  name = excluded.name,
  kind = excluded.kind,
  state = coalesce(excluded.state, public.retailers.state),
  config = public.retailers.config || excluded.config,
  -- Keep hand-written adapters (JB Hi-Fi, Target, BIG W, Kmart) and their switch.
  platform = case when public.retailers.adapter in ('none', 'shopify', 'woocommerce') then excluded.platform else public.retailers.platform end,
  adapter = case when public.retailers.adapter in ('none', 'shopify', 'woocommerce') then excluded.adapter else public.retailers.adapter end,
  enabled = case when public.retailers.adapter in ('none', 'shopify', 'woocommerce') then excluded.enabled else public.retailers.enabled end,
  blocked_reason = case when public.retailers.adapter in ('none', 'shopify', 'woocommerce') then excluded.blocked_reason else public.retailers.blocked_reason end;
